Added translation of Wasteland
LWHK/NuclearCraft pull request #2
Opened 2020-08-07 15:31 UTC by ghostbird03

2020-08-08 00:54 UTC, WuzgXY-GitHub requested changes

2020-08-08 00:54 UTC, WuzgXY-GitHub commented on src/main/resources/assets/nuclearcraft/lang/zh_cn.lang
> -# 核电工艺游戏内配置文件
|Feedback Priority|
|---|
|⏳ Sand / Non-blocking but requires future consideration|

何必删掉呢

2020-08-08 00:54 UTC, WuzgXY-GitHub commented on src/main/resources/assets/nuclearcraft/patchouli_books/guide/zh_cn/categories/fission.json
> +	"description": "核裂变能，禁忌之果...",
|Feedback Priority|
|---|
|⛰ Mountain / **Blocking and requires immediate action**|

不不不你不能删了它

2020-08-08 00:54 UTC, WuzgXY-GitHub commented on src/main/resources/assets/nuclearcraft/patchouli_books/guide/zh_cn/categories/fusion.json
> +	"description": "一种无尽的能源...",
|Feedback Priority|
|---|
|⛰ Mountain / **Blocking and requires immediate action**|

同上

2020-08-08 00:54 UTC, WuzgXY-GitHub commented on src/main/resources/assets/nuclearcraft/patchouli_books/guide/zh_cn/categories/heat_exchanger.json
> +	"description": "\"经典热力学是具有普遍内容的唯一物理理论。我深信在其基本概念适用的范围内是绝不会被推翻的...\"$(br2)——阿尔伯特·爱因斯坦",
|Feedback Priority|
|---|
|⛰ Mountain / **Blocking and requires immediate action**|

同上
『唯一的具有普遍内容的物理理论』会不会更好

2020-08-08 17:23 UTC, ghostbird03 commented on src/main/resources/assets/nuclearcraft/patchouli_books/guide/zh_cn/categories/fusion.json
> +	"description": "一种无尽的能源...",
新版本没push，我准备在配置文件改动后一块push。
现在本地版本是改好省略号的。

2020-08-08 17:28 UTC, ghostbird03 commented on src/main/resources/assets/nuclearcraft/patchouli_books/guide/zh_cn/categories/heat_exchanger.json
> +	"description": "\"经典热力学是具有普遍内容的唯一物理理论。我深信在其基本概念适用的范围内是绝不会被推翻的...\"$(br2)——阿尔伯特·爱因斯坦",
这是《哈工大研究生热力学》第九章教案、《热学绪论》教案、《高等工程热力学》教案等里的翻译版本，除了少个“的”。原文是“具有普遍内容的唯一的物理理论”
因此我认为这个翻译版本已经成为中国学界事实上的标准翻译所以保留了原句。（尽管我也觉得这话翻译的怪怪的）

2020-08-08 17:29 UTC, ghostbird03 commented on src/main/resources/assets/nuclearcraft/lang/zh_cn.lang
> -# 核电工艺游戏内配置文件
之前排查语言文件缺漏时候删掉方便看有没有缺失，后来忘了加回去了xd

2020-08-08 17:31 UTC, ghostbird03 commented on src/main/resources/assets/nuclearcraft/patchouli_books/guide/zh_cn/categories/fission.json
> +	"description": "核裂变能，禁忌之果...",
新版本没push，我准备在配置文件改动后一块push。
现在本地版本是改好省略号的。其他同此处。
在意的话可以等我把配置文件改好push了再merge这个pr。

2020-08-08 17:31 UTC, ghostbird03 commented on src/main/resources/assets/nuclearcraft/patchouli_books/guide/zh_cn/categories/heat_exchanger.json
> +	"description": "\"经典热力学是具有普遍内容的唯一物理理论。我深信在其基本概念适用的范围内是绝不会被推翻的...\"$(br2)——阿尔伯特·爱因斯坦",
这是《哈工大研究生热力学》第九章教案、《热学绪论》教案、《高等工程热力学》教案等里的翻译版本，除了少个“的”。原文是“具有普遍内容的唯一的物理理论”
因此我认为这个翻译版本已经成为中国学界事实上的标准翻译所以保留了原句。（尽管我也觉得这话翻译的怪怪的）

2020-08-09 00:20 UTC, WuzgXY-GitHub commented on src/main/resources/assets/nuclearcraft/patchouli_books/guide/zh_cn/categories/heat_exchanger.json
> +	"description": "\"经典热力学是具有普遍内容的唯一物理理论。我深信在其基本概念适用的范围内是绝不会被推翻的...\"$(br2)——阿尔伯特·爱因斯坦",
:+1:

2020-08-09 00:21 UTC, WuzgXY-GitHub commented on src/main/resources/assets/nuclearcraft/lang/zh_cn.lang
> -# 核电工艺游戏内配置文件
LOL

2020-08-09 00:21 UTC, WuzgXY-GitHub approved these changes

2020-08-09 00:23 UTC, merged